host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API-Users Support
    url: http://www.swagger.io/support
  description: Documentação da API de Users.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger API-Users
  version: "1.0"
paths: {}
swagger: "2.0"
